# Generated by Django 3.1.7 on 2021-05-05 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2021, 5, 5))),
                ('Name_video', models.CharField(max_length=100, null=True, verbose_name='name_video')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('Description', models.CharField(max_length=1500, verbose_name='description')),
                ('Date', models.DateField(default=datetime.date(2021, 5, 5))),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.TimeField()),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cvision.inquiry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cvision.person')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encoding', models.JSONField()),
                ('Description', models.CharField(default='Описание изображения отсутствует', max_length=1500, verbose_name='description')),
                ('FileName', models.CharField(default='Имя файла отсутствует', max_length=1500, verbose_name='filename')),
                ('DateAdded', models.DateField(default=datetime.date(2021, 5, 5))),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cvision.person')),
            ],
        ),
    ]
